### ISSUE TITLE
Could this be the repo for the CSS v2 site?

### ISSUE THREAD

**Issue by sierkje** [CodeSelfStudy/codeselfstudy-drupal-project#1]
I don't know whether it's a good idea to rename this repo, or to create a new one, but this repo seems to be the one where we could develop the new D8 site. Right?

**Comment by j127** [comment]
Sure... we could rename this one.

**Comment by j127** [comment]
"Drupal-8-Website"?

**Comment by j127** [comment]
@sierkje - I thought you already had access to this one. Just added you.

**Comment by sierkje** [comment]
Closing, because "fixed" (i.e. D8 code will go here.)
